module.exports = {
    togglePause: 'cycle pause',
    stop: 'stop',
    status: 'show-progress',
    seekBackward: 'seek -5',
    seekForward: 'seek +5',
    bigSeekBackward: 'seek -30',
    bigSeekForward: 'seek +30',
    increaseSpeed: 'multiply speed 1.1',
    decreaseSpeed: 'multiply speed 0.9',
    resetSpeed: 'set speed 1',
    decreaseVolume: 'add volume -5',
    increaseVolume: 'add volume 5',
    mute: 'cycle mute',
    toggleFullscreen: 'cycle fullscreen',
    toggleSubtitle: 'cycle sub',

    loop: "cycle loop",
    switch_angle: "cycle angle",
    switch_audio: "cycle audio",
    vo_ontop: "cycle ontop",
    vo_border: "cycle border",
    frame_drop: "cycle framedrop",
    switch_vsync: "cycle vsync",
    sub_visibility: "cycle sub-visibility",
    forced_subs_only: "cycle sub-forced-only",
    ass_use_margins: "cycle ass-use-margins",
};

